# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a4bf8d672a8e73424192ce2771a45a08cb259f1f0558a16baaf4dc5af037fa77b5f13076e78d1a4de0a26a36f40a2e4f19d8b9fdce3c5505f7bf33709052df

test:
  secret_key_base: 0a1a3eeeece01d5349356e838c28acf1cf0c629486321924b34fdf534fbad1dda18c42edc47204f3b98c61e37fec523e3c0ec897274b0d2b01b6e7e6d2a4951d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
